### ISSUE TITLE
New matrix types and access methods

### ISSUE THREAD

**Issue by gnzlbg** [sebcrozet/nalgebra#100]
_Partially-dynamic matrices:_
Sometimes when working with dynamic matrices I know e.g. the number of columns but not the number of rows before hand. This can be used to speedup lookup and slices by relying on a compile time constant for offsetting indices. This can also speed matrix slices since it allows to return stack allocated slices instead of dynamic vectors.

_Dynamic matrices of bounded size:_
Sometimes I know the maximum size a matrixis going to have, but not the exact size (it is still dynamic). This knowledge allows matrices to be stack allocated. Is the same argument as for the already implemented dynamic vectors of bounded size.

_Mutable matrix slices_:
Right now the matrix methods `col_slice` and `row_slice` return an immutable `DVec<N>`. It would very useful to have a way to return a mutable slice to a matrix' sub-matrix (rows and cols are two common sub-matrices).

**Comment by sebcrozet** [comment]
The second point is now implemented!

The last point is still interesting and worth the work. But I cannot think of a nice way of implementing the first one at the moment (and it seems less important than the rest).

**Comment by sebcrozet** [comment]
The new version of nalgebra implements the first and third points. The second one will no longer be supported.
