### ISSUE TITLE
Compilation fails on rust 1.0 stable

### ISSUE THREAD

**Issue by ecogiko** [sebcrozet/nalgebra#128]
Hello!

I am using glium as a dependency which in turn uses nalgebra and the build fails because of one of the macros. This happens on rust 1.0 stable.

    ico@arch ted $ uname -a
    Linux arch 4.0.2-1-ARCH #1 SMP PREEMPT Thu May 7 06:47:54 CEST 2015 x86_64 GNU/Linux
    ico@arch ted $ multirust show-default
    multirust: default toolchain: stable
    multirust: default location: /home/ico/.multirust/toolchains/stable

    rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)
    cargo 0.2.0-nightly (efb482d 2015-04-30) (built 2015-04-30)

    ico@arch ted $ cargo build
       Compiling nalgebra v0.2.13
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:295:22: 295:64 error: cannot transmute to or from a type that contains type parameters in its interior [E0139]
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:295                     &mem::transmute::<&$t<N>, [N; $dim * $dim]>(self)[i + j * $dim]
                                                                                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:288:1: 308:3 note: in expansion of index_impl!
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat.rs:63:1: 63:22 note: expansion site
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:295:22: 295:64 error: cannot transmute to or from a type that contains type parameters in its interior [E0139]
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:295                     &mem::transmute::<&$t<N>, [N; $dim * $dim]>(self)[i + j * $dim]
                                                                                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:288:1: 308:3 note: in expansion of index_impl!
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat.rs:115:1: 115:22 note: expansion site
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:295:22: 295:64 error: cannot transmute to or from a type that contains type parameters in its interior [E0139]
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:295                     &mem::transmute::<&$t<N>, [N; $dim * $dim]>(self)[i + j * $dim]
                                                                                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:288:1: 308:3 note: in expansion of index_impl!
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat.rs:200:1: 200:22 note: expansion site
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:295:22: 295:64 error: cannot transmute to or from a type that contains type parameters in its interior [E0139]
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:295                     &mem::transmute::<&$t<N>, [N; $dim * $dim]>(self)[i + j * $dim]
                                                                                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:288:1: 308:3 note: in expansion of index_impl!
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat.rs:309:1: 309:22 note: expansion site
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:295:22: 295:64 error: cannot transmute to or from a type that contains type parameters in its interior [E0139]
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:295                     &mem::transmute::<&$t<N>, [N; $dim * $dim]>(self)[i + j * $dim]
                                                                                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:288:1: 308:3 note: in expansion of index_impl!
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat.rs:436:1: 436:22 note: expansion site
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:295:22: 295:64 error: cannot transmute to or from a type that contains type parameters in its interior [E0139]
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:295                     &mem::transmute::<&$t<N>, [N; $dim * $dim]>(self)[i + j * $dim]
                                                                                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat_macros.rs:288:1: 308:3 note: in expansion of index_impl!
    /home/ico/.multirust/toolchains/beta/cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.2.13/src/structs/mat.rs:569:1: 569:22 note: expansion site
    error: aborting due to 6 previous errors
    Could not compile `nalgebra`.

    To learn more, run the

**Comment by sebcrozet** [comment]
Hi!

I think your version of `nalgebra` is a bit too old. This compilation issue has been fixed a while ago, using a reference `&[N; $dim * $dim]` instead of an array `[N; $dim * $dim]`. See https://github.com/sebcrozet/nalgebra/blob/master/src/structs/mat_macros.rs#L295

**Comment by sebcrozet** [comment]
Yeah, looks like `glium` depends on the version 0.2.12 of `nalgebra` (https://github.com/tomaka/glium/blob/master/Cargo.toml#L40), which wont compile with the 1.0 release of rustc.

**Comment by ecogiko** [comment]
Thanks! There is already a PR in the glium repository to update the versions. I guess the answer is to wait a bit.
