### ISSUE TITLE
Rectangular matrices

### ISSUE THREAD

**Issue by yongqli** [sebcrozet/nalgebra#136]
What should I do if I have rectangular matrices? Would I have to implement it myself?

**Comment by sebcrozet** [comment]
Unfortunately rectangular matrices are not implemented yet in `nalgebra`. I tried a few months ago but the macro system was not powerful enough do to this in a clean way. I believe this should be possible now.

**Comment by sebcrozet** [comment]
Though you can use a `DMat` for rectangular matrices, but this will allocate (its size is not fixed at compile time).

**Comment by sebcrozet** [comment]
Fixed by #218. Rectangular matrices of any dimension are now supported.
