### ISSUE TITLE
Add associated types?

### ISSUE THREAD

**Issue by yongqli** [sebcrozet/nalgebra#137]
Please see this <a href="http://stackoverflow.com/questions/30845261/functional-dependencies-in-rust">question</a>. I would love to be able to write:

```
#[allow(non_snake_case)]
pub struct Multivar𝒩<M: SquareMat> {
    μ: M::V,
    Σ: M,
}
```

**Comment by sebcrozet** [comment]
I'd love to use associated types wherever possible, but the current stable version of the compiler doesn't support them well enough (they tend to cause lots of ICEs).

In particular, the modification of `SquareMat` you are suggesting here was part of my initial work to add associated types (see the branch https://github.com/sebcrozet/nalgebra/tree/associated_types), but the compiler failed to compile without crashing so I stopped this development until the next stable release of the compiler (which will hopefully fix those bugs).

**Comment by yongqli** [comment]
Thanks. Interestingly I was able to get the `associated_types` branch to compile on nightly rust, but not the benchmarks.

**Comment by yongqli** [comment]
It might also make sense to use associated constants for things like `Eye` and `Dim`.

**Comment by aepsil0n** [comment]
This has been fixed by the trait reform.
