### ISSUE TITLE
Rot3's look_at should be static

### ISSUE THREAD

**Issue by Binero** [sebcrozet/nalgebra#154]
Function in question: https://github.com/sebcrozet/nalgebra/blob/0e7116e3bbcbdf84d4d89f3e3d0e91c1f28b7046/src/structs/rot.rs#L191

This function does not require the previous state of the Rot3, and should be static. I am willing to make this static, but that'd require breaking the API.

Please greenlight this or provide an alternative.

**Comment by sebcrozet** [comment]
I agree with your reasoning. `look_at` (as well as `look_at_z`) should be static and you are welcome to make this happen!

**Comment by Binero** [comment]
I'll get to it sometime this week hopefully.

**Comment by Binero** [comment]
PR: https://github.com/sebcrozet/nalgebra/pull/155

**Comment by sebcrozet** [comment]
Related PR merged. Closing this issue.
