### ISSUE TITLE
Arrays with arbitrary number of dimensions

### ISSUE THREAD

**Issue by gabrielelanaro** [sebcrozet/nalgebra#157]
I've seen that nalgebra support Vec (1D) and Matrix (2D) I was wondering if nalgebra aims to support tensors with arbitrary number of  dimensions (ND)

**Comment by MrMormon** [comment]
With more dimensions comes more operations defined on them, you know.

**Comment by sebcrozet** [comment]
Tensors with arbitrary number of dimensions are not in my current development plans, though anyone is welcome to contribute to the project by adding them!

**Comment by sebcrozet** [comment]
Higher order tensors will not be implemented (except perhaps 3D, but not an _arbitrary_ number of dimension). See the crate ndarray for some basic support. Closing this.
