### ISSUE TITLE
Incorrect look_at definition

### ISSUE THREAD

**Issue by yggie** [sebcrozet/nalgebra#158]
Correct me if I am wrong, but the definition for `Rot3.look_at` uses the look-at formula for column-major ordered matrices ([link](https://github.com/sebcrozet/nalgebra/blob/6fee70bd19a42454ce896f48f1b4b034565262f3/src/structs/rot.rs#L213-L217)) but the matrix constructor works in row-major order ([link](https://github.com/sebcrozet/nalgebra/blob/6fee70bd19a42454ce896f48f1b4b034565262f3/src/structs/mat.rs#L141-L151)), this would mean that the `Rot3.look_at` calculations are incorrect. I would be happy to open a PR to fix this issue, but I would really like a second pair of eyes to tell me I am not seeing things…

**Comment by sebcrozet** [comment]
Fixed by #175 .
