### ISSUE TITLE
Initialization from moved Vec without allocation

### ISSUE THREAD

**Issue by andrewcsmith** [sebcrozet/nalgebra#167]
I'd like to be able to move some data into a DMat, rather than copy it. What I would need is a function like this:

```rust
pub fn from_col_vec_move(nrows: usize, ncols: usize, vec: Vec<N>) -> DMat<N>;
```

Or whatever you want to call it. Should be very simple (just don't call `to_vec()`), so I'm happy to do it if you have a preference for what name to use. Alternatively, it could be generic over a trait that allows for moving the data from either `DVec` or `Vec`.

**Comment by sebcrozet** [comment]
I've written a slightly more flexible version of your proposal. Once #170 is merged, you will be able to use `DMat::from_{row,col}_iter` with anything that implements the `IntoIter` trait. That includes `Vec` (which will actually consume the `Vec` without allocation/deallocation).

**Comment by andrewcsmith** [comment]
hugely helpful. thanks!
