### ISSUE TITLE
`len()` methods return usize

### ISSUE THREAD

**Issue by Binero** [sebcrozet/nalgebra#173]
The `VecX::len()` methods seem to return `usize`. Shouldn't it return the `N` type parameter?

**Comment by sebcrozet** [comment]
`VecX::len()` has the same meaning as `Vec::len()` from the standard library. Thus, it is the number of element on the vector. If you are searching for the vector norm, use `nalgebra::norm(&the_vector)` or `nalgebra::sqnorm(&the_vector)` to obtain the squared norm.
