### ISSUE TITLE
Support multiplying f64 * Vec3<f64> and so on

### ISSUE THREAD

**Issue by jorendorff** [sebcrozet/nalgebra#182]
Rust doesn't allow `impl<N> Mul<Vec3<N>> for N`, but na could provide an `impl` for the most common types, `f32` and `f64`, just as a convenience. In my case, it'd be nice; I'm using `f32` exclusively.

If this is something you'd take, let me know. I'll send a PR.

**Comment by sebcrozet** [comment]
That would be useful indeed!

Actually, I thought `impl Mul<Vec3<f32>> for f32` was not permited either since both `Mul` and `f32` come from external crates.

**Comment by jorendorff** [comment]
Yeah - the actual rules are complicated enough that I failed to get to the end of the niko blog post explaining them. :) But
