### ISSUE TITLE
Why use full names instead of abbreviations?

### ISSUE THREAD

**Issue by yongqli** [sebcrozet/nalgebra#192]
Hi,

I'm curious as to why you've decided to use full names instead of abbreviations? It seems to be the rust style to use abbreviations, i.e. `by_ref` instead of `by_reference`, `len` instead of `length`, etc.

**Comment by sebcrozet** [comment]
This has been a bit discussed [there](https://github.com/sebcrozet/nalgebra/issues/176). The main reason is that as new structure were added, some abbreviations were becoming meaningless or ambiguous. In particular, some features (e.g. similarity transformations) were hard to recognize while browsing the rustdoc-generated documentation.
