### ISSUE TITLE
Confusing results from Perspective3

### ISSUE THREAD

**Issue by iirelu** [sebcrozet/nalgebra#204]
I'm porting my code from using raw linear algebra maths to using nalgebra, and I'm getting some weirdness in Perspective3.

![](https://cloud.githubusercontent.com/assets/3432543/18330982/b4e663a0-7553-11e6-8e95-5ba6a759a46a.png)

In order for the bottom block to have identical results to the top block, I need to invert two elements of the matrix:

```rust
// ??????????
pers[2][2] *= -1.0;
pers[2][3] *= -1.0;
```

There's probably a good reason for this, but I'm not getting it. Help?

**Comment by sebcrozet** [comment]
The sign of those two entries depend on the handedness convention you choose. The choice of nalgebra is to flip the z-axis in order to switch to a left-handed coordinate system. This is motivated by OpenGL-based applications.

**Comment by iirelu** [comment]
Right, that makes sense. Thank you.

(Later down the line I found out I didn't even need to do those inverts any more, so that's probably a good thing)
