### ISSUE TITLE
Transform trait for Matrices?

### ISSUE THREAD

**Issue by robo-hamburger** [sebcrozet/nalgebra#205]
The docs mention "This is typically implemented by matrices which transform vector" but this does not appear to be the case and there are no examples. Searching the code comes up with nothing either.

It would be quite useful if this trait were implemented for Matrix1-4. A bespoke Scale type might also be useful. Currently, I am using `Matrix4::from_diagonal(&Vector4::new(...))` but that is more verbose than I would prefer.

**Comment by sebcrozet** [comment]
Actually, "implemented by matrices" is quite misleading (I should change that). Here, "matrices" refer the specific types dedicated to transformations, i.e., `Rotation3`, `Isometry3`, and `Similarity3` (which are usually understood as matrices by computer-graphics people).

Regarding scaling, if you need uniform scaling, you may use `Similarity3` (what you do is the only solution for non-uniform scaling through).

**Comment by sebcrozet** [comment]
Also, The next release will add more computer-graphics oriented operations to Matrix3/4. In particular, as you suggest, Matrix3/4 will be able trantform 2D/3D points and vectors, following the implied rules of projective geometry (e.g. vectors won't be affected by the rightmost column of the matrix).
I am still unsure whether this will be implemented behind a trait or not (the next release will also modernify the traits as the current design mostly dates from before Rust 1.0).

**Comment by robo-hamburger** [comment]
Awesome! I am working around this by making my own non-uniform scale struct and implementing transform for it. I think that should meet my needs for the time being (not sure if this is a good idea but it seems to work).

The nice thing about the Transform trait is I can have a generic function to transform that works with most of nalegbra. Though I guess in this case not so much :)

**Comment by sebcrozet** [comment]
Fixed by #218. Matrices now implement the `Transfomation` trait. Moreover, I added some [constructors](http://nalgebra.org/cg_recipes/#transformations-using-matrix4) to Matrix4 to create, e.g., a non-uniform scaling matrix.
