### ISSUE TITLE
Support the decimal crate

### ISSUE THREAD

**Issue by eugene-bulkin** [sebcrozet/nalgebra#206]
Is there any way we can support the `d128` used in the `decimal` crate for use in matrices? e.g. I want to have a matrix of `d128` values and do stuff with them.

Note: This would require impl-ing `BaseNum` and `Cast<f64>` for `d128`. The last one seems sketchy to me since that cast is not precise.

**Comment by sebcrozet** [comment]
We could optionally support this behind a feature. Implementors of the `Cast` trait are not bound to strong accuracy requirements. They are just expected to return the closest représentable value.
The main difficulty here is that `BaseFloat` requires `num::Float` to be implemented and it looks like `d128` is still missing all the trigonometric functions.

**Comment by aepsil0n** [comment]
@eugene-bulkin in today's world like all traits that need to be implemented are outside of `nalgebra`. So if this is still a relevant issue, I would suggest to pursue the integration of `decimal` with `alga` and `num-traits` to make these operations work.

I don't think there is anything to be done here though. Therefore I am going to close this issue.
