### ISSUE TITLE
Compiler overflow evaluating the requirement `<&_ as std::ops::Mul<&_>>::Output`

### ISSUE THREAD

**Issue by djmcgill** [sebcrozet/nalgebra#211]
It's possible to cause a compiler overflow by trying to multiply a reference without a concrete type. The minimal example below is duplicated both on 0.10.1 from crates.io and master from the repository.

```
extern crate nalgebra;
use nalgebra::Vector3;

pub fn thing() {
    let f: f32 = 1.0;
    let x1: Vector3<f32> = &Vector3::<f32>::z() * f; // Fine

    // overflow evaluating the requirement `<&_ as std::ops::Mul<&_>>::Output`
    let x2: Vector3<f32> = &Vector3::z() * f;
}
```

The full error message can be found here: https://gist.github.com/djmcgill/d4afe13a3c5b4145897be0916496f73e

**Comment by icefoxen** [comment]
I get an even more mysterious but similar explosion in this program:

```
extern crate nalgebra as na;

fn main() {
    let height: f64 = 40.0;
    // overflow evaluating the requirement `<&_ as std::ops::Add<&_>>::Output`
    for y in -(height / 2)..(height / 2) {
        println!("aiee: {}", y);
    }
}
```

Output here: https://gist.github.com/icefoxen/3812c3ba0dfe7a3dad4e3196c4ca1d66

Thank you!  :heart:
