### ISSUE TITLE
impl Cast for DVector and DMatrix

### ISSUE THREAD

**Issue by sbidin** [sebcrozet/nalgebra#215]
Implementations of `Cast` [seem to be missing](http://nalgebra.org/doc/nalgebra/trait.Cast.html) for the `DVector` and `DMatrix` types, among others. Is there a reason for this and would a patch be welcome?

**Comment by sebcrozet** [comment]
There is no good reason for it to be missing. Though there is no need to make a patch as it is already implemented on the yet-to-be-released next version of nalgebra (see #207 and the implementation [here](https://github.com/sebcrozet/nalgebra/blob/nexgen/src/core/conversion.rs#L11-L37)).
