### ISSUE TITLE
cargo test generate lots of Broken MIR

### ISSUE THREAD

**Issue by sebcrozet** [sebcrozet/nalgebra#219]
Looks like the compiler (MIR generator ?) fails to match type-level integers with the result of a type-level integer operation, e.g., it thinks that `U3 != <U4 as Sub<U1>>::Output`.

**Comment by jonas-schievink** [comment]
A similar looking error was reported in https://github.com/rust-lang/rust/issues/39367

**Comment by aepsil0n** [comment]
Is this still happening in current Rust? The aforementioned issue has since been resolved and I can't see anything happening, when running `cargo test`.

**Comment by sebcrozet** [comment]
No, this is no longer happening, let's close this.
