### ISSUE TITLE
VectorN * VectorN and / doesn't work anymore

### ISSUE THREAD

**Issue by arturoc** [sebcrozet/nalgebra#224]
Not sure if this is intentional but since vectors are no based on Matrix and only NM * MN matrices can be multiplied that removes the possibility of multiplying for example Vector3 x Vector3  as `Vector3::new(a.x * b.x, a.y*b.y, a.z*b.z)` which is pretty common in graphics vector math libraries

**Comment by sebcrozet** [comment]
Yes, componentwise multiplication and division are no longer possible using operator overloading. They have been replaced by the methods `.component_mul`, `.component_mul_mut`, `.component_div`, `.component_div_mut`.

It seems I forgot to mention this on the changelog, sorry ! (I keep this issue open until I update the changelog).
