### ISSUE TITLE
Typo in model-view-projection recipe?

### ISSUE THREAD

**Issue by jeffparsons** [sebcrozet/nalgebra#229]
From http://nalgebra.org/cg_recipes/#build-a-mvp-matrix or https://github.com/sebcrozet/nalgebra/blob/master/examples/mvp.rs:

```
// The combination of the model with the view is still an isometry.
let model_view = model * view;
```

I think this should be:

```
let model_view = view * model;
```

**Comment by sebcrozet** [comment]
You were right, there was an error. Thanks!
