### ISSUE TITLE
array-interop: request for feedback

### ISSUE THREAD

**Issue by vitiral** [sebcrozet/nalgebra#238]
Please see anowell/are-we-learning-yet#14. I would like for the major rust array crates to be able to have interop without friction. I would love your feedback

**Comment by aepsil0n** [comment]
I had not seen this issue before, but are you aware of `mint` (see #270)? It seems like a very similar idea from my point of view. Perhaps there is a proliferation of standards, after all.

**Comment by aepsil0n** [comment]
Closing, since #270 has been merged by now. If there are concrete issues beyond mint in terms of improving interoperability, feel free to open new ones for those.
