### ISSUE TITLE
Implement IntoIterator for matrices

### ISSUE THREAD

**Issue by WaDelma** [sebcrozet/nalgebra#241]
There seems to be a method for iterating through matrix, but there isn't `IntoIterator` implementation.
If this is just oversight and there isn't any implementation problems, it would be nice to have the implementation.

**Comment by sebcrozet** [comment]
Yes, that's just an oversight!

**Comment by aepsil0n** [comment]
After merging #242, this is only missing an implementation of `IntoIterator` for `Matrix`. I think this would be limited to matrices that own their storage. However, the current `OwnedStorage` trait does not envision this use case. So here is a proposal for how this could be made to work in steps:

- Implement `IntoIterator` for all implementations of `OwnedStorage`, namely `MatrixArray` and `MatrixVec`.
- Add a bound `IntoIterator<Item=N>` to `OwnedStorage<N,...>`. (This part is backwards-incompatbile, as it might break existing implementations outside `nalgebra`.)
- Implement `IntoIterator` for matrices with an owned storage, delegating to the storage implementation.

@sebcrozet as this is technically a backwards-incompatible change, would you have any objections to doing it in this way?
