### ISSUE TITLE
Add conversion of quaternion/rotation matrix 3 to Euler angles.

### ISSUE THREAD

**Issue by sebcrozet** [sebcrozet/nalgebra#243]

**Comment by lolzballs** [comment]
I'm looking into using this library for a program I'm writing and this would be a nice feature. I would add it myself, but I'm not familiar enough with the library to help implement it right now.

**Comment by aepsil0n** [comment]
I am happy to help out with questions about the library, if you want to add the feature.

Just for reference, I am going to leave some instructions here for you (or anyone else, who wants to add the feature at some point). Have a look at these two `from_euler_angles` methods, to understand how these objects are constructed from Euler angles:

- [src/geometry/quaternion_construction.rs:131](https://github.com/sebcrozet/nalgebra/blob/9066ce484dd1ae8835f7c6e5c4208ddbbfd84a33/src/geometry/quaternion_construction.rs#L131)
- [src/geometry/rotation_specialization.rs:164](https://github.com/sebcrozet/nalgebra/blob/9066ce484dd1ae8835f7c6e5c4208ddbbfd84a33/src/geometry/rotation_specialization.rs#L164)

Assuming you are familiar with the math, you would have to create `to_euler_angles` counterparts for both. I would add them as intrinsic methods (probably directly in `src/geometry/quaternion.rs` and `src/geometry/rotation.rs`).
