### ISSUE TITLE
v0.11.3 is breaking change due to serde update

### ISSUE THREAD

**Issue by yongqli** [sebcrozet/nalgebra#246]
The `serde` update to 1.0 is breaking and thus I believe `v0.11.3` should have been `v0.12`. I believe that any Cargo.toml that used `nalgebra = "0.11"` will now no longer compile.

**Comment by yongqli** [comment]
As a work-around for anyone else currently facing the problem: using `nalgebra = "=0.11.2"` fixes it.

**Comment by sebcrozet** [comment]
You're right. Sorry for the mistake. I've yanked the version 0.11.3 to prevent further breakage and published 0.12.0.
