### ISSUE TITLE
Add tensor product operation

### ISSUE THREAD

**Issue by cormac-obrien** [sebcrozet/nalgebra#248]
The tensor product of two matrices is particularly useful for physics applications.

This might be somewhat expensive to implement given that the tensor product matrix of an `m ⨯ n` matrix with a `p ⨯ q` matrix is of dimension `mp ⨯ nq`. It may become easier once Π-types are added to Rust.

**Comment by sebcrozet** [comment]
This is implemented as the Kronecker product with the `.kronecker(...)` method. Pi-types would indeed make the implementation cleaner. In the mean time, the typenum-based implementation should work as expected.
