### ISSUE TITLE
Use forwarding impls of Serialize/Deserialize for wrapper types

### ISSUE THREAD

**Issue by Ralith** [sebcrozet/nalgebra#249]
A unit quaternion currently encodes in JSON as something like `{"value":{"coords":{"data":[0.0,0.0,1.0,0.0]}}}`, and in TOML as something like `[[[[0, 0, 0, 1]]]]`. Even a `Vector3` ends up as `{"data":[0.0,0.0,0.0,1.0]}`. This doesn't seem useful, and is in particular very unfriendly for data intended to be written by hand. If Serialize/Deserialize implementations were written to forward to the ultimate storage, rather than automatically derived, the resulting encodings would be much friendlier. If nobody has any objections, I'm happy to do the grunt work of making it happen.

**Comment by sebcrozet** [comment]
No objection from me. Seems like a great idea!
