### ISSUE TITLE
Better support with Complex<N> types

### ISSUE THREAD

**Issue by atilag** [sebcrozet/nalgebra#266]
I was trying to make some matrix operations using complex types, e.g: 
```
let mut temp1 = DMatrix::<Complex<f64>>::identity(5usize, 5usize);
let mut temp2 = DMatrix::<Complex<f64>>::identity(5usize, 5usize);
let _ = temp1.dot(&temp2);
let _ = temp1.kronecker(&temp2);
```
... but seems like Complex<N> types are not well supported by the library. 
 
```
error: no method named `dot` found for type `na::Matrix<num::Complex<f64>, na::Dynamic, na::Dynamic, na::MatrixVec<num::Complex<f64>, na::Dynamic, na::Dynamic>>` in the current scope
  --> src/lib.rs:70:19
   |
70 |     let _ = temp1.dot(&temp2);
   |                   ^^^
   |
   = note: the method `dot` exists but the following trait bounds were not satisfied: `num::Complex<f64> : alga::general::Ring
```

Is there any plan for supporting them?
Thanks!!

**Comment by sebcrozet** [comment]
Yes, we intend to support them but this won't be possible before assignment operators (`AddAssign`, `MulAssign` etc.) are implemented for `Complex`. There is an [open PR](https://github.com/rust-num/num/pull/274) for the num-complex crate but it has not been merged yet unfortunately.

**Comment by atilag** [comment]
Ok, I see you PR, Thanks :)
In the meantime, I did my own "Complex" implementation, but I had an error while trying to use the [dot() function](http://nalgebra.org/rustdoc/src/nalgebra/core/matrix.rs.html#867-987):
```
error: no method named `dot` found for type `na::Matrix<complex::Complex, na::Dynamic, na::Dynamic, na::MatrixVec<complex::Complex, na::Dynamic, na::Dynamic>>` in the current scope
  --> src/lib.rs:80:19
   |
80 |     let _ = temp1.dot(&temp2);
   |                   ^^^
   |
   = note: the method `dot` exists but the following trait bounds were not satisfied: `complex::Complex : alga::general::Ring`

error: aborting due to previous error
```
Seems like an implementation of "alga::general::Ring" trait is needed... sounds kind of complex for me to implement this trait on my Complex implementation. 
Will your PR take this into account?

**Comment by atilag** [comment]
Ok, I see you PR, Thanks :)
In the meantime, I did my own "Complex" implementation, but I had an error while trying to use the [dot() function](http://nalgebra.org/rustdoc/src/nalgebra/core/matrix.rs.html#867-987):
```
error: no method named `dot` found for type `na::Matrix<complex::Complex, na::Dynamic, na::Dynamic, na::MatrixVec<complex::Complex, na::Dynamic, na::Dynamic>>` in the current scope
  --> src/lib.rs:80:19
   |
80 |     let _ = temp1.dot(&temp2);
   |                   ^^^
   |
   = note: the method `dot` exists but the following trait bounds were not satisfied: `complex::Complex : alga::general::Ring`

error: aborting due to previous error
```
Seems like an implementation of "alga::general::Ring" trait is needed... sounds kind of complex for me to implement this trait on my Complex implementation. 
Will your PR take this into account?

**Comment by atilag** [comment]
@sebcrozet anything I can do to help you with this?

**Comment by atilag** [comment]
So I tried [this PR](https://github.com/rust-num/num/pull/274), but seems like I can't multiply two Matrices, like:
```
let temp1 = DMatrix::<Complex<f64>>::identity(5usize, 5usize);
let temp2 = DMatrix::<Complex<f64>>::identity(5usize, 5usize);
println!(" Multiplication: {}", temp1 * temp2 );
```
Compiler error:
```
error[E0308]: mismatched types
  --> src/lib.rs:56:36
   |
56 |     println!("Multiplication: {:?}", temp1 * temp2);
   |                                    ^^^^^ expected struct `num::Complex`, found struct `na::Matrix`
   |
   = note: expected type `num::Complex<f64>`
              found type `na::Matrix<num::Complex<f64>, na::Dynamic, na::Dynamic, na::MatrixVec<num::Complex<f64>, na::Dynamic, na::Dynamic>>`
```

**Comment by sebcrozet** [comment]
Sorry for the delay, I'm currently in holidays so I'll take a closer look at that next week. One way to help integrate complex type on nalgebra is perhaps to make another PR rust-num/num#274 for the num crate, but taking in account the reviewer requests, i.e., to implement `NumAssign` traits.

The next step is to implement the trait `Ring` and all its supertrait for `Complex`. This should be done on the [alga](https://github.com/sebcrozet/alga) crate. This should allow operations like dot product to work.

Regarding your last compilation error, I'm not sure what the problem is so I'll have to investigate more closely.

**Comment by sebcrozet** [comment]
@atilag It seems that rust-num/num#274 has been merged. I tried both of your examples (after a `cargo update`) and both seem to work now. Does it work for you as well now?

Note that `println!(" Multiplication: {}", temp1 * temp2 );` won't compile though because matrices with complex components do not implement `Display` yet. This will fixed in a future release of nalgebra.

**Comment by sebcrozet** [comment]
Of course, `println!(" Multiplication: {:?}", temp1 * temp2 );` will compile because it requires `Debug` instead of `Display`.

**Comment by atilag** [comment]
Yeah! it works now :) ... I'll try the rest of my use-cases.
Thanks for the effort @sebcrozet !
