### ISSUE TITLE
`from_euler_angles` has wrong documentation?

### ISSUE THREAD

**Issue by Binero** [sebcrozet/nalgebra#269]
The function `from_euler_angles` is implemented for both [rotations](https://github.com/sebcrozet/nalgebra/blob/1471031ac45e8b69558259a44726087a3383e511/src/geometry/rotation_specialization.rs#L181) and [quaternions](https://github.com/sebcrozet/nalgebra/blob/1471031ac45e8b69558259a44726087a3383e511/src/geometry/quaternion_construction.rs#L153).

I have been playing around with these functions, and it seems to me that the order of parameters claimed is not correct. Going from experimentation, it seems that the order of parameters is "pitch, yaw, roll", and not "roll, pitch, yaw", as claimed.

**Comment by aepsil0n** [comment]
I have not written that code, but it looks consistent with most of what you find online. Looking at the matrix, roll is rotation around the x-axis, pitch around the y-axis and yaw around the z-axis. Given the usual convention that the z-axis goes upwards and the x-axis is, where things (like airplanes) point to, it seems pretty correct to me.

Can you elaborate what you mean by "playing around" and how that led you to believe the order is wrong? Is it possible you expect different axes to mean "up/down", "forward/backward" and "left/right"?

**Comment by Binero** [comment]
That could very well be the case. I am assuming a right handed coordinate system.

**Comment by sebcrozet** [comment]
nalgebra assumes a right handed coordinate system. It also assumes that you multiply your vector on right-hand-side (`rotation * vector`). If you multiply on the left-hand-side (`vector * rotation`) you will inverse-rotate your vector. Here is a test that seems correct:

```rust
extern crate nalgebra as na;

use na::Rotation3;

fn main() {
    let (r, p, y) = (0.4, 10.8, 1.9);
    let roll  = Rotation3::from_euler_angles(r, 0.0, 0.0);
    let pitch = Rotation3::from_euler_angles(0.0, p, 0.0);
    let yaw   = Rotation3::from_euler_angles(0.0, 0.0, y);

    println!("roll:\n{}", roll);
    println!("pitch:\n{}", pitch);
    println!("yaw:\n{}", yaw);

    let rpy = Rotation3::from_euler_angles(r, p, y);

    println!("Is composition correct: {}", yaw * pitch * roll == rpy);
}
```

And the output:

```
roll:
RotationBase matrix {
  ┌                      ┐
  │  1.000  0.000  0.000 │
  │  0.000  0.921 -0.389 │
  │ 0.000  0.389  0.921 │
  └                      ┘
}

pitch:
RotationBase matrix {
  ┌                      ┐
  │ -0.194 0.000 -0.981 │
  │ 0.000  1.000 0.000 │
  │  0.981 0.000 -0.194 │
  └                      ┘
}

yaw:
RotationBase matrix {
  ┌                      ┐
  │ -0.323 -0.946  0.000 │
  │  0.946 -0.323  0.000 │
  │ 0.000  0.000  1.000 │
  └                      ┘
}

Is composition correct: true
```

It seems that all individual matrices are correct, and the composition of the three is correct as well.

**Comment by aepsil0n** [comment]
@Binero have you come to a conclusion on this issue?

Do you perhaps have any suggestion on how we might improve the documentation to make this more obvious?

**Comment by Binero** [comment]
I do not have a conclusion. I haven't tried since. The code I used to play with the rotations has been replaced by code that doesn't use this function at all. It's a non-issue for me at the moment.
