### ISSUE TITLE
panic 'Matrix index out of bounds.' in check_homogeneous_invariants (impl TCategory for TAffine)

### ISSUE THREAD

**Issue by ennis** [sebcrozet/nalgebra#271]
The following code:
```rust
let local_transform : Affine3<f32> = try_convert(Matrix4::<f32>::identity()).unwrap();
```
results in a panic 'Matrix index out of bounds.' in check_homogeneous_invariants: [src/geometry/transform.rs, line 104](https://github.com/sebcrozet/nalgebra/blob/7a62b68c38ca4689a81694b5da505abf8872a4b2/src/geometry/transform.rs#L104-L104)

```rust
fn check_homogeneous_invariants<N, D, S>(mat: &SquareMatrix<N, D, S>) -> bool
        where N: Scalar + Field + ApproxEq,
              D: DimName,
              S: Storage<N, D, D>,
              N::Epsilon: Copy {
        mat.is_invertible()                   &&
        mat[(D::dim(), D::dim())] == N::one() &&
        (0 .. D::dim()).all(|i| mat[(D::dim(), i)].is_zero())
    }
```

Shouldn't `D::dim()` be `D::dim()-1` ?

**Comment by aepsil0n** [comment]
Thank you for reporting this. I issued a PR adding a little regression test for now. I do not think, that this had been tested anywhere before.
