### ISSUE TITLE
Optional feature: abomonation support

### ISSUE THREAD

**Issue by aepsil0n** [sebcrozet/nalgebra#277]
I am currently working on modelling computational fluid dynamics as [timely dataflow](https://github.com/frankmcsherry/timely-dataflow) programs. Since serialization can be a limiting communication overhead for such programs, `timely-dataflow` uses a very efficient, but also completely unsafe serialization library called [abomonation](https://github.com/frankmcsherry/abomonation).

In order to use `nalgebra` types in timely dataflow graphs, they need to implement the `Abomonation` trait. Do you think it would be okay to add an optional feature to support this? There is [a crate](https://github.com/mystor/abomonation_derive) to derive the trait automatically that would make the implementation straightforward.

I would be happy to provide the pull request for this, if this is acceptable.

**Comment by sebcrozet** [comment]
I think it is acceptable to support several serialization formats besides `serde`. Thus `Abomonation` could be a good candidate as long as it is maintained and remains optional.

**Comment by frankmcsherry** [comment]
Another option, whose appeal depends in part on the complexity of the `nalgebra` types, is for @aepsil0n and others to wrap unsupported types and implement the `Abomonation` trait for those wrappers. This is less ergonomic, all things considered, but it may reduce the management burden for other projects (moving the burden to the users). It may not be possible, though, if the types have lots of private fields and such.

I think it would be great to have lots of things implement `Abomonation`, but I do want to point out the alternatives. :)

**Comment by aepsil0n** [comment]
Wrapper types induce a lot of extra churn though, because all the functionality has to be delegated, which is *a lot* in the case of `nalgebra`. If I were faced with that decision, I would rather maintain my own fork or work around the missing impl than working with wrapper types.

btw @frankmcsherry I suppose it is impossible to make `abomonation` conform to serde's abstraction?

**Comment by frankmcsherry** [comment]
It is "probably" impossible. Abomonation relies on the ability to arrange a `&mut [u8]` as a valid in-memory representation of the type in question.

Another possibility is looking in to timely dataflow using multiple serialization formats. Right now it is baked in to the communication layer, where there is a blanket implementation of the `Serialize` trait for types implementing `Abomonation`, but which could try to do something more tasteful. Making them all play nice together could be awkward, but it is a good question (I don't know the answer) whether this should be the job of the type provider (e.g. `nalgebra`) or of the type consumer (e.g. `timely-dataflow`).

I'll look into this, but you are totally welcome to post a similar issue over on the timely repo (roughly: "timely communication support for multiple serialization formats").
