### ISSUE TITLE
Benchmarks vs C++ libraries

### ISSUE THREAD

**Issue by ChristopherRabotin** [sebcrozet/nalgebra#284]
I was wondering whether there were any benchmarks of nalgebra versus C++ libraries like armadillo or BLAS/LAPACK. I see that there's a Rust native implementation of some LAPACK functions.

I'd be especially interested in such a benchmark since Rust isn't too far off from C++ in execution time.

Thanks

**Comment by WaDelma** [comment]
@sebcrozet has [done](https://github.com/sebcrozet/nalgebra/issues/274#issuecomment-319795315) some benchmarks against Rust implementations and bindings.

**Comment by ChristopherRabotin** [comment]
These are pretty cool. Would it be possible to extend those to armadillo, since this library is faster than BLAS on large matrices?

**Comment by sebcrozet** [comment]
I guess extending those to armadillo and Eigen would be possible. For example we could create bindings for the few matrix decompositions (specialized for dynamically-sized matrix with the `double` scalar type) we want to benchmark and call them from rust inside of the benchmark functions with the same inputs generated for the rust benchs. (I don't have the time to work on this right now though.)

Note that all the benchmarks are on the `bench` folder of the [rust_linalg_bench](https://github.com/sebcrozet/rust_linalg_bench) repository and are run with `cargo bench`.
