### ISSUE TITLE
Limitations of the Schur decomposition?

### ISSUE THREAD

**Issue by ChristopherRabotin** [sebcrozet/nalgebra#292]
I _might_ be using the library incorrectly, but if not, then I may have found a limitation in the Schur decomposition algorithm on a 2x2 matrix. The decomposition as done in the following code leads to a unitary matrix which is identity and the supposedly upper triangular matrix is actually the original matrix.
[Wolfram Alpha validation](https://www.wolframalpha.com/input/?i=schur+decomposition&rawformassumption=%7B%22F%22,+%22SchurDecompositionCalculator%22,+%22theMatrix%22%7D+-%3E%22%7B%7B2.78,12.89%7D,%7B-6.97,3.14%7D%7D%22&rawformassumption=%7B%22C%22,+%22schur+decomposition%22%7D+-%3E+%7B%22Calculator%22%7D) does not return the same result.

```rust
extern crate nalgebra as na;
use na::DMatrix;
fn main() {
    let mat = DMatrix::from_row_slice(2, 2, &[2.78, 12.89, -6.97, 3.14]);
    let (unitary, triang) = mat.clone().real_schur().unpack();
    println!("mat = {}", mat);
    println!("{} {}", unitary, triang);
}
```

Output:
```
> cargo run
   Compiling naexamples v0.1.0 (file:///home/chris/Workspace/rust/naexamples)
    Finished dev [unoptimized + debuginfo] target(s) in 1.96 secs
     Running `target/debug/naexamples`
mat = 
  ┌             ┐
  │  2.78 12.89 │
  │ -6.97  3.14 │
  └             ┘



  ┌     ┐
  │ 1 0 │
  │ 0 1 │
  └     ┘

 
  ┌             ┐
  │  2.78 12.89 │
  │ -6.97  3.14 │
  └             ┘

```

_Note_: this is a blocker for #283 .

**Comment by sebcrozet** [comment]
I think both nalgebra and wolfram are correct. The real schur decomposition is not unique. So if your 2x2 matrix has complex eigenvalues, any rotation matrix `R` can be chosen such that `M = R (R* M R) R*` where `M` designs the original matrix. Then the real-shur decomposition is composed of the unitary matrix `R` and the matrix `R* M R`. nalgebra (and Eigen as well) choose `R = Id`. I believe wolfram choose something else because it also restricts the 2x2 blocks to have opposite anti-diagonal elements.

Perhaps a method could be added to `Schur` to make its 2x2 blocks anti-diagnoal elements opposite as well.

**Comment by ChristopherRabotin** [comment]
I agree that the Schur decomposition is not unique. However, isn't the other matrix supposed to be an upper triangular matrix? That's also what Wikipedia says in [Statement section](https://en.wikipedia.org/wiki/Schur_decomposition#Statement).

**Comment by sebcrozet** [comment]
The Real Schur decomposition is not the same as the Schur decomposition. The former is actually upper-quasi-triangular by keeping 2x2 blocks on its diagonal to avoid requirering complex values. You can refer to the section 7.4 "Eigenvalues and Real Schur forms" of the Golub et al. "Matrix Computations", 4-th edition book if you have it (as you mentioned in #283 ).

(By the way, I meant the `RealSchur` structure in my last comment. Sorry if that confused you, I'll eddit the comment to reflect that.).

**Comment by ChristopherRabotin** [comment]
Thanks, I was not aware of this situation concerning complex eigenvalues.

In the interest of potential future readers, I have attached the relevant excerpts from the book.
![part_1](https://user-images.githubusercontent.com/4823784/31314949-e6fa02c2-abc9-11e7-9a54-0e7d2dcf1f66.png)
![part_2](https://user-images.githubusercontent.com/4823784/31314950-f14f93f4-abc9-11e7-8851-a2d5a1708dcd.png)

**Comment by sebcrozet** [comment]
Thanks for the excepts !
