### ISSUE TITLE
Add trait for Point2?

### ISSUE THREAD

**Issue by awestlake87** [sebcrozet/nalgebra#294]
as of 0.13.1 this doesn't work:
```rust
let p1 = geometry::Point2::new(0.0, 0.0);
let p2 = geometry::Point2::new(0.0, 0.0);

let sum = p1 + p2;
```
the trait std::ops::Add is not satisfied for Point2. I'm not all that familiar with this library, but I think this should work, especially since this piece of code works:
```rust
let p1 = Vector2::new(0.0, 0.0);
let p2 = Vector2::new(0.0, 0.0);

let sum = p1 + p2;
```

**Comment by aepsil0n** [comment]
No, I am sorry, but it should not. `Point` is specifically designed to mean a point, i.e. a location in space, not a vector. So this is a deliberate limitation of the API. Adding two points is not meaningful in this context.

However, you should be able to add a vector to a point, as far as I know.

**Comment by awestlake87** [comment]
Ah ok, I think I understand now. I should have read the documentation more closely.
