### ISSUE TITLE
Does/can `Matrix` implement `Zero`?

### ISSUE THREAD

**Issue by paulkernfeld** [sebcrozet/nalgebra#301]
I see that the `alga` crate defines a trait called `Zero`, but it looks to me like `Matrix` does not implement it. Is this correct? If so, could I open a pull request for it?

**Comment by WaDelma** [comment]
Do you mean `Identity<Additive>` from `alga` or `Zero` from `num-traits`? Both of them seem to be missing from `Matrix`, but are implemented for more specific matrices.

**Comment by paulkernfeld** [comment]
Ah, good point. I think I had meant `Zero` from `num-traits`, but to be honest I'm not entirely sure. I eventually found the definition. In case anyone else comes looking for it, it's [here](https://github.com/sebcrozet/nalgebra/blob/9066ce484dd1ae8835f7c6e5c4208ddbbfd84a33/src/core/construction.rs#L343) in src/core/construction.rs.
