### ISSUE TITLE
Program crashes when inserting row in 0x0 matrix

### ISSUE THREAD

**Issue by bno1** [sebcrozet/nalgebra#306]
Running:
```rust
let m: na::DMatrix<u32> = na::DMatrix::zeros(0, 0);

m = m.insert_row(0, 1);
m = m.insert_column(0, 1);
```

Results in:
```
thread 'main' panicked at 'attempt to subtract with overflow', /home/bno1/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.13.1/src/core/edition.rs:558:20
```
If I switch `insert_row` with `insert_column` the crash doesn't happen.

Shouldn't this [1] be `0..ncols`?

[1] https://github.com/sebcrozet/nalgebra/blob/master/src/core/edition.rs#L558

**Comment by aepsil0n** [comment]
Does the change you suggest fix your issue?

I have not thought this through yet admittedly. But note, that there is some special treatment for the last column right above in the code, so I am not too surprised it only goes to `ncols - 1` there.

**Comment by bno1** [comment]
@aepsil0n I didn't try it. I looked over the code closely now and I understand what is happening.
When a row extension takes place (i.e. ninsert rows are added starting with index i) it has to reorganize data in the linear buffer of the matrix. The author unrolled the first iteration of the loop because it has less data to be copied (I don't understand why is this) but didn't consider that `ncols` might be 0.
Without unrolling that iteration the loop would looked like:
```rust
    for k in (0 .. ncols).rev() {
        ptr::copy(ptr_in.offset((k * nrows + i) as isize),
                  ptr_out.offset(curr_i as isize),
                  nrows);

        curr_i -= new_nrows;
    }
```
which in theory would behave properly for `ncols = 0`, the for loop would be skipped entirely.

The solution it think it is to check if `ncols != 0` and return immediately if that's true. Or maybe in the beginning of resizing functions check if all the dimensions are 0 and if so just allocate a 0-sized buffer and avoid the rest of the logic.

**Comment by aepsil0n** [comment]
Ah, i see, now I understand this somewhat better, thanks. Perhaps @sebcrozet could tell us what that optimization is about. I wonder whether there is a benchmark for this somewhere. Nonetheless, feel free to submit a PR to address it, if you want.

**Comment by sebcrozet** [comment]
Sorry for the late answer. The special case for the last column of the resized matrix is actually not an optimization.

It is necessary because overwise the `ptr::copy` would read elements outside of the bounds of `data`. Indeed, the first iteration of the `for` loop proposed by @bno1 will read `nrows` elements after the index `(ncols - 1) * nrows + i`, e.g., the element with index `ncols * nrows + i - 1`. This will cause problem whenever `i > 0` as the `data` is assumed to contain at most `new_nrows * ncols` elements.

I will fix this today.
