### ISSUE TITLE
Vector and RowVector cross product

### ISSUE THREAD

**Issue by nilgoyette** [sebcrozet/nalgebra#308]
use nalgebra::Vector3;
    let p1 = Vector3::new(1.0, 2.0, 3.0);
    let p2 = Vector3::new(1.0, 5.0, 7.0);
    print!("{}", p1.cross(&p2));
    -1
    -4
     3

    use nalgebra::RowVector3;
    let p1 = RowVector3::new(1.0, 2.0, 3.0);
    let p2 = RowVector3::new(1.0, 5.0, 7.0);
    print!("{}", p1.cross(&p2));
    [ -1 -4 -4 ]

I don't understand why the results are different! The `Vector3` is the right answer. What does `RowVector3` is calculating? As a standard user (and non-math expert), I'm expecting the results to be equal. Is there a reason not to?

**Comment by aepsil0n** [comment]
Yes, I think you found a bug. Look at [line 882 in src/core/matrix.rs](https://github.com/sebcrozet/nalgebra/blob/master/src/core/matrix.rs#L882) and compare with the column vector implementation above. This looks like copy & paste gone wrong to me. The comments imply @sebcrozet wanted to do some clean-up there anyway at some point.

Would you be interested in fixing this and writing a regression test to help out? :)

**Comment by nilgoyette** [comment]
Yeah, sure, I'll fix this today.
