### ISSUE TITLE
Investigate moving to brendanzab/algebra as a basis for nalgebra

### ISSUE THREAD

**Issue by brendanzab** [sebcrozet/nalgebra#32]
We are currently in the process of simplifying the numeric traits in the standard libraries (see rust-lang/rfcs#369). Perhaps we could move to [algebra](https://github.com/brendanzab/algebra/) as a basis for nalgebra?

**Comment by sebcrozet** [comment]
I started working on that.

This is currently being done in parallel to the improvement of the `algebra` crate itself.
A few of those traits have been implemented in d29ff5332930afdd3b1d468e712891da62fab3ef

**Comment by brendanzab** [comment]
I wonder if it will be possible to allow for better integration between cgmath and nalgebra then... even then, perhaps I might consider switching back if I'm happy enough with the end result :)

**Comment by sebcrozet** [comment]
Since #218 , we use [alga](https://github.com/sebcrozet/alga) as a basis for **nalgebra**. Closing this.
