### ISSUE TITLE
Implement Deref for Matrix with Target = [T]

### ISSUE THREAD

**Issue by robsmith11** [sebcrozet/nalgebra#321]
I'm trying to write a bunch of utility functions to make scientific computing more convenient in Rust like
```
fn median(x:&[f64]) -> f64
fn kurtosis(x:&[f64]) -> f64
```
These seem to work well because I can pass either a `&[f64]` or a `&Vec<f64>` because `Vec<T>` implements `Deref` for `Target = [T]`.

Would it make sense for `Matrix` to also implement `Deref` for `Target = [T]`?  Then these functions that take a slice reference could be used directly with `Matrix` without having to call `as_slice()`.

**Comment by sebcrozet** [comment]
There already exists implementations of `Deref` for some vector/matrix types (with a `Target` which is not a slice) so it is not possible to add others. So using `.as_slice()` here is unavoidable unfortunately.

**Comment by robsmith11** [comment]
Ok, understood
