### ISSUE TITLE
distance and EuclideanSpace

### ISSUE THREAD

**Issue by nilgoyette** [sebcrozet/nalgebra#326]
I'm currently using `(p1 - p2).norm();` to get the distance between 2 points. I tested doing it "by hand"

    ((p1.x - p2.x).powi(2) + (p1.y - p2.y).powi(2) + (p1.z - p2.z).powi(2)).sqrt();

and it's 2x faster. I was quite surprised and I was about to keep this code when I realized that I can use `nalgebra::distance(p1, p2);` to get the distance between 2 points. My problem is that I'm unable to call this function!

    the trait bound `nalgebra::Matrix<f64, nalgebra::U1, nalgebra::U3, nalgebra::MatrixArray<f64, nalgebra::U1, nalgebra::U3>>: alga::linear::vector::EuclideanSpace` is not satisfied

I tried `use`ing `EuclideanSpace` to get the trait in scope but I think it's not publicly exported...? I'm probably missing something simple! What am I supposed to import?

**Comment by WaDelma** [comment]
The [trait](https://docs.rs/alga/0.5.3/alga/linear/trait.EuclideanSpace.html) comes from `alga` crate which provides traits for abstract algebra and linear algebra.

You shouldn't need to import it to use the function, but it seems like it's only implemented for `Point`s.

**Comment by nilgoyette** [comment]
Haha, ok, I never realized that there's a `Point` type! I was using a `RowVector3`. I'll try that. Thank you.

**Comment by nilgoyette** [comment]
@WaDelma Do you know if it's possible to multiply a `Point` with an 3x3 affine? Using a `RowVector` I could write `(p * affine) + translation` bit now I can't.

**Comment by Ralith** [comment]
Normally you right-multiply points by transforms, i.e. `(xf * p)`. The documentation on [points and transforms](http://nalgebra.org/points_and_transformations/) might be helpful.

**Comment by nilgoyette** [comment]
I'm now using `Point`s everywhere and I still can't use `distance`

    no method named `distance` found for type `&nalgebra::Point<f64, nalgebra::U3>` in the current scope

It works when I add `use alga::linear::EuclideanSpace;` Are you sure I shouldn't need to import anything?

**Comment by WaDelma** [comment]
Odd... When you use trait as bound on function or struct you shouldn't need to use the trait.
Can you post some kind of minimal example?

**Comment by sebcrozet** [comment]
@nilgoyette You do need to `use alga::linear::EuclideanSpace;` to be able to call the method `distance` as in `point1.distance(&point2)`. On the other hand you don't need to import this trait if you use the `distance` free function `nalgebra::distance(&point1, &point2)`.

**Comment by nilgoyette** [comment]
Oups, I mixed those calls. You're right. Thank you.
