### ISSUE TITLE
Important bug: `geometry::UnitQuaternion::to_rotation_matrix` is incorrect

### ISSUE THREAD

**Issue by ChristopherRabotin** [sebcrozet/nalgebra#327]
The algorithm in [to_rotation_matrix](https://github.com/sebcrozet/nalgebra/blob/master/src/geometry/quaternion.rs#L541) actually returns the transpose DCM matrix. In other words, if a quaternion `beta` represents the attitude change from frame B to N, then calling `to_rotation_matrix` returns the rotation from the **N** frame to the **B** frame. This is either incorrect, or there should be an important warning in the documentation.

My reference is "Analytical Mechanics of Space Systems" by Schaub and Junkins, 3rd edition. This book is considered **the** main reference for attitude representations and control.

I would be more than happy to correct this bug, especially since it's a relatively small bug.

![Definition](https://user-images.githubusercontent.com/4823784/37881460-89307854-3055-11e8-9721-79c7af972c83.jpg)
![Direct cosine matrix](https://user-images.githubusercontent.com/4823784/37881462-92e751ba-3055-11e8-803b-6bbdc77bc125.jpg)
![Schub and Junkins, 3rd ed.](https://user-images.githubusercontent.com/4823784/37881459-7a9677d0-3055-11e8-899f-3acaeada4d5c.jpg)

**Comment by ChristopherRabotin** [comment]
Here is a reproducible example, using Example 3.6 of page 106 (cf. attachments).

```rust
extern crate nalgebra;
use nalgebra::Matrix3;
use nalgebra::geometry::{Quaternion, UnitQuaternion};

fn main() {
    let beta = Quaternion::new(0.961798, -0.145650, 0.202665, 0.112505);
    let q_dcm = UnitQuaternion::from_quaternion(beta).to_rotation_matrix();
    let e_dcm = Matrix3::new(
        0.892539,
        0.157379,
        -0.422618,
        -0.275451,
        0.932257,
        -0.234570,
        0.357073,
        0.325773,
        0.874526,
    );
    println!("delta: {:}", q_dcm.matrix() - e_dcm);
    println!("transpose delta: {:}", q_dcm.matrix().transpose() - e_dcm);
}
```

Output:
```
delta: 
  ┌                                                                                  ┐
  │ 0.000000023207650134970947        -0.4328295396211126         0.7796909509133554 │
  │        0.43282888612741294  0.00000039089706649342304         0.5603434766304045 │
  │        -0.7796913775104919        -0.5603431544106402      0.0008999247076062478 │
  └                                                                                  ┘


transpose delta: 
  ┌                                                                                  ┐
  │ 0.000000023207650134970947   -0.000001113872587055198  -0.0000003775104919223615 │
  │  0.00000046037888740135813  0.00000039089706649342304 -0.00000015441064021848305 │
  │  -0.0000000490866446378746  0.00000047663040458889583      0.0008999247076062478 │
  └                                                                                  ┘

```

![Example 3.6](https://user-images.githubusercontent.com/4823784/37881606-1e49c33a-3058-11e8-98fd-bcb18ae2e32e.jpg)
![Referenced equations](https://user-images.githubusercontent.com/4823784/37881607-25a07b42-3058-11e8-86cc-44babd6f8c6e.jpg)

**Comment by ChristopherRabotin** [comment]
@sebcrozet Any objection if I open a PR on this?

**Comment by sebcrozet** [comment]
Thank you for the detailed explanation and references. I did not know the term "Direction Cosine Matrix" so there are some things I might not understand correctly. I've managed to find an electronic version of the 2nd edition of the book you mention. I understand the formula for converting Euler parameters to a rotation matrix is derived from trigonometric identities (3.91) substituted into the formula to convert axis-angle representation to a rotation matrix (3.72):
![image](https://user-images.githubusercontent.com/1734958/38354924-99ac8858-38bb-11e8-86e4-d05c52147232.png)

I did not read the text far enough to exactly see what `{b}` and `{n}` are, but I assume that they aretwo orthogonal basis. Anyway, it appears that this formula is also the transpose of what is done in nalgebra [there](https://github.com/sebcrozet/nalgebra/blob/master/src/geometry/rotation_specialization.rs#L141-L169).

So either nalgebra does both wrong, or all this is just a matter of opposite conventions. I know nothing about the modeling of space systems, but it appears that nalgebra follows the convention commonly used in computer-graphics. References are for example [glm](https://github.com/g-truc/glm/blob/master/glm/gtc/quaternion.inl#L618-L644) (which is column-major, so the entry Result[1][0] is at the first row of the second column), or the book Physics-Based Animation from Erleben et.al:

![img_1192_lowres](https://user-images.githubusercontent.com/1734958/38356257-8f7d36a8-38bf-11e8-956b-adaab325bf99.jpg)

In addition, I'm not sure your first affirmation is correct:
> In other words, if a quaternion beta represents the attitude change from frame B to N, then calling to_rotation_matrix returns the rotation from the N frame to the B frame.

If I understand correctly, the correct behavior is to making sure that:
```
q * v == q.to_rotation_matrix() * v
```
for all unit quaternion `q` and all vector `v`. This identity is already tested [there](https://github.com/sebcrozet/nalgebra/blob/master/tests/geometry/quaternion.rs#L96-L104). Am I missing something? Any detail on what I think to be a different convention on your references is welcome.

**Comment by ChristopherRabotin** [comment]
I agree with the identity that you provide and test.

Redoing some proofs right now, I confirm that it's a notation difference. In Schaub, to avoid confusion, the DCMs are noted as [BN] to mean a conversion from frame *N* to frame *B*: `v_B = [BN] * v_N` (i.e. the vector `v` in the B frame is equal to the DCM [BN] times the vector `v` in the N frame). This is clear from equation 4.20 in Schaub 4th ed.

A good quick test is using the quaternion `Q = (sqrt(2)/2, 0, 0, sqrt(2)/2)` which corresponds to a rotation of 90 degrees about the third axis.

Since there is no bug but only a notation difference, I'll close this issue.
