### ISSUE TITLE
Matrix multiplication broken for custom scalar types

### ISSUE THREAD

**Issue by dthul** [sebcrozet/nalgebra#331]
Since I work a lot with color data I implemented my own `RGB` scalar type such that I can treat colors like scalars.

## The Problerm
When I initialize two `na::DMatrix<RGB>` matrices and multiply them, the result is random garbage. I stepped through the nalgebra code with a debugger and found the bug:

* The [Mul implementation](https://github.com/sebcrozet/nalgebra/blob/7b249f8966a79f81b2ad687904457019b21b835d/src/core/ops.rs#L511) for two &na::Matrix objects first (unsafely) creates an uninitialized matrix. This new matrix is supposed to be filled with the multiplication result before `mul()` returns.
* `mul_to()` is called, specifying the uninitialized matrix as the storage destination
* `mul_to()` in turn [calls the BLAS specialization](https://github.com/sebcrozet/nalgebra/blob/7b249f8966a79f81b2ad687904457019b21b835d/src/core/ops.rs#L676) to actually perform the multiplication
* The BLAS specialization [checks whether the type stored in the matrix is f32 or f64](https://github.com/sebcrozet/nalgebra/blob/7b249f8966a79f81b2ad687904457019b21b835d/src/core/blas.rs#L488) and _does nothing otherwise_
* Since my scalar type is neither f32 nor f64, this leads to the fact that the resulting matrix stays uninitialized

## Possible Solution
I think the BLAS specialization should only exist for na::Matrix<f32, ...> and na::Matrix<f64, ...> types in the first place or at least throw a runtime error for other types. `mul_to()` then needs to have another code path to multiply matrices that are other types of scalars without BLAS.

**Comment by sebcrozet** [comment]
Hi! Sorry for the very late answer. This issue has been fixed in the version 0.15 of nagebra. Please reopen if you encounter a similar problem again.
