### ISSUE TITLE
compile error on latest nightly (rustc 1.27.0-nightly (2f2a11dfc 2018-05-16))

### ISSUE THREAD

**Issue by ennis** [sebcrozet/nalgebra#338]
Compilation fails on rustc 1.27.0-nightly (2f2a11dfc 2018-05-16) with the following log:

https://gist.github.com/ennis/d8a52edd3d831922d046a558906172be

Works fine on beta. This may be a rustc regression, but i'm not sure.

**Comment by WaDelma** [comment]
It should already be fixed in #333

**Comment by ennis** [comment]
@WaDelma I think you are referring to the warnings "warning: duplicate definitions with name `new` (E0592)", that I included in the log. But the actual compilation errors (starting from https://gist.github.com/ennis/d8a52edd3d831922d046a558906172be#file-nalgebra-build-log-txt-L100) seem unrelated to this issue.

**Comment by sebcrozet** [comment]
This does look like a regression on rustc. Maybe related to https://github.com/rust-lang/rust/issues/50825 or at least quite similar to the issue mentioned in https://github.com/rust-lang/rust/issues/50825#issuecomment-389796962 .

**Comment by sebcrozet** [comment]
I believe this will fixed by https://github.com/rust-lang/rust/pull/50876.

**Comment by ennis** [comment]
It looks like the issue is fixed in the latest nightly.

**Comment by sebcrozet** [comment]
Great! This can be closed then.
