### ISSUE TITLE
Conversion to and from static arrays

### ISSUE THREAD

**Issue by aepsil0n** [sebcrozet/nalgebra#36]
This is motivated mainly to allow a seamless interaction with piston libraries. Piston internally uses https://github.com/PistonDevelopers/vecmath, which are generic functions on static arrays ([T, ..n] or [[T, ..n], ..m]). Thus to interface with the libraries it is crucial to be able to convert vectors and matrices to and from static arrays seamlessly.

I don't know whether this warrants changing the internal representation to arrays. Transitioning from cgmath I find this a bit cumbersome to work around.

**Comment by tomjakubowski** [comment]
Maybe I'm missing something here, but isn't implementing `From<[T; N]>` and `Into<[T; N]>` for e.g. `VecN<T>` sufficient?

**Comment by sebcrozet** [comment]
You're correct, implementing those two traits is the way to go! They did not exist (and neither did DSTs) when this issue was created.

**Comment by sebcrozet** [comment]
Into and From are now implemented for matrices and vectors since v0.11.1. For other structures, the user can access their vector or matrix representations (and then use Into and From) if needed. Closing this.
