### ISSUE TITLE
Generic cross

### ISSUE THREAD

**Issue by nilgoyette** [sebcrozet/nalgebra#360]
I was updating an old project and I can't compile my generic impl anymore.

    use alga::general::{Real, Ring};
    impl<T: Real + Ring> StreamlineExt for [Point3<T>] {
        ...
        // v1 and v2 are Point3<T>
        let p = v1.coords.cross(&v2.coords);
        ...
    }

I added `+ Ring` because the compiler tells me to add it, but I still get this error:

    note: the method `cross` exists but the following trait bounds were not satisfied:
        `T : alga::general::specialized::Ring`

What am I missing?

**Comment by sebcrozet** [comment]
That's odd. What versions of  alga and nalgebra are you depending on? Chances are that the version of alga you depend on does not match the version of alga nalgebra itself depends on.

**Comment by nilgoyette** [comment]
Awww, dammit, I was still at  `alga v0.5`. Thank you!
