### ISSUE TITLE
impl Send for SliceStorage{,Mut}?

### ISSUE THREAD

**Issue by YaLTeR** [sebcrozet/nalgebra#366]
I cannot say for sure but after a quick glance over the methods I think this should be safe? It's not automatically implemented because of the raw pointer `*mut N`. Perhaps `Sync` too?

If it is indeed safe, I think this should do the trick, in `src/base/matrix_slice.rs`:
```rust
        unsafe impl<'a, N: Scalar + Send, R: Dim, C: Dim, RStride: Dim, CStride: Dim> Send
            for $T<'a, N, R, C, RStride, CStride>
        {}
```

**Comment by sebcrozet** [comment]
Now that you mention it, I agree a`SliceStorage` should indeed be `Send + Sync` because they represent only immutable references. A `SliceStorageMut` on the other hand should only be `Send` since it is not safe for several threads to share a mutable reference.

**Comment by bugaevc** [comment]
> A SliceStorageMut on the other hand should only be Send since it is not safe for several threads to share a mutable reference.

I beg to differ, that's not how `Sync` works. [`&mut T`, for example, is `Sync`](https://play.rust-lang.org/?gist=5e138af7ce3365e8dc7c49b7f4176a35&version=stable&mode=debug&edition=2015). `T: Sync` means _it is safe for several threads to share `&T` references_, i.e. any internal mutability `T` implements is thread-safe. The fact that it would be unsound if several threads had multiple `&mut T` references at the same time is irrelevant (and prevented by the language disallowing multiple `&mut T`s, not by type author making their types `!Sync`).

So to say it again, `Sync` has to do whether `&T` operations are thread-safe (e.g. `Rc::clone(&self)` is not, so `Rc: !Sync`), not `&mut T` operations (which surely aren't).

**Comment by sebcrozet** [comment]
Thank you for the explanation @bugaevc! It seems understanding of `Sync` was incorrect.
