### ISSUE TITLE
Use quickcheck for testing

### ISSUE THREAD

**Issue by aepsil0n** [sebcrozet/nalgebra#50]
[QuickCheck](https://github.com/BurntSushi/quickcheck) allows to test properties on arbitrary input. This prevents a larger class of bugs than example-based unit testing. My proposal is to use it for nalgebra's test suite. For convenience this involves implementing `quickcheck::Arbitrary` for most types. These impls should be public (i.e. not only compiled for the test suite), so that user code can use these implementations to write own tests that involve nalgebra types.

We may think about making this an optional feature, as it adds a dependency to nalgebra.

btw, I volunteer to do this at some point, unless there are any objections.

TODO
- [x] Implement `quickcheck::Arbitrary` for all types.
- [x] Migrate test suite to use quickcheck.

**Comment by aepsil0n** [comment]
I've started to work on this. It should be done soon.

**Comment by aepsil0n** [comment]
Now I realize how much time has passed, since I posted the last comment. I need to dig up this once again to see how it was going ;)

**Comment by sebcrozet** [comment]
Fixed by #218. We now use quickcheck for testing.
