### ISSUE TITLE
Add pseudoinverse, SVD

### ISSUE THREAD

**Issue by Jragonmiris** [sebcrozet/nalgebra#78]
Pseudoinverse and singular value decomposition calculation, while difficult, is useful if nphysics (or some animation library) ever wants to implement Jacobian-based inverse kinematics methods. It's doable with just the transpose, but incredibly imprecise.

**Comment by sebcrozet** [comment]
SVD and pseudo-inverse will be released on the next version of nalgebra. See #274 .
