### ISSUE TITLE
UnitQuat should have to_rot4

### ISSUE THREAD

**Issue by andrewrk** [sebcrozet/nalgebra#81]
I'm not sure about this, but I believe that what I want is to have a 4x4 matrix which represents affine transformations and I want to add a rotation to that. So I create a UnitQuat and then I want to modify my 4x4 matrix. So I would call `unit_quat.to_rot().mult(my_4x4_matrix)`. But that does not work since to_rot returns a 3x3 matrix.

Perhaps a `to_rot4()` function should be added which fills in 0's and a 1 on the diagonal for convenient use with a 4x4 transformation matrix?

**Comment by aepsil0n** [comment]
You can call `unit_quad.to_rot().to_homogeneous()` to do just that.

**Comment by sebcrozet** [comment]
And note that to call `.to_homogeneous()`, you have to import the `nalgebra::ToHomogeneous` trait. In general, `.to_homogeneous()` will take and algebraic object, assume it is expressed in the trivial basis of dimension `Dim::dim()`, and immerse it into a projective space (aka. "homogeneous" coordinates).

Hence, it will add a 0 to vectors, a 1 to points, add a line and column filled with zero (everywhere but in the diagonal) to matrices, and assemble correctly the isometric (`Iso`) transformation into a matrix combining both the translation and rotation (using right-multiplication as a convention).

**Comment by andrewrk** [comment]
Thank you for the explanation. For someone whose linear algebra skills are underdeveloped this information is helpful.

 If this kind of info were in the docs I think it would make it possible for people who are not already experts to use the library. (I say this in a "let's improve things" attitude rather than a criticism)
