### ISSUE TITLE
how do I make a 4x4 identity matrix?

### ISSUE THREAD

**Issue by andrewrk** [sebcrozet/nalgebra#82]
I see this: http://tomaka.github.io/glium/nalgebra/struct.Mat4.html#method.new_identity

But why does it take a `dim: usize` argument? We already know it is 4x4.

**Comment by andrewrk** [comment]
found it: http://tomaka.github.io/glium/nalgebra/struct.Mat4.html#method.one

if you put:

`/// Returns the identity matrix` before the method then it would have shown up in the docs and my Ctrl+F would have found it.

**Comment by sebcrozet** [comment]
The current comment for the function `One::one()` is "Returns the multiplicative identity." (http://nalgebra.org/doc/nalgebra/trait.One.html) While it could be found by a Ctrl+F on the trait doc, rustdoc does not seem to inline the comments of trait functions for its implementors… So I think this is more a limitation on the documentation generator.
