### ISSUE TITLE
#[repr(C)] for structs?

### ISSUE THREAD

**Issue by jarrett** [sebcrozet/nalgebra#85]
Should the vector and matrix structs have `#[repr(C)]`? Without that, I suspect the compiler could [rearrange the memory layout of the structs](http://doc.rust-lang.org/book/ffi.html#interoperability-with-foreign-code). That would cause weird and hard-to-debug errors when passing pointers to C APIs like OpenGL. E.g. when calling `glBufferData` or `gluniformmatrix4fv`.

I apologize if I'm mistaken about this. I'm new to Rust.

**Comment by aepsil0n** [comment]
As far as I understand the code, the C ordering is intended and some unsafe parts of the implementation might even rely on it. So I am generally in favour. #97 even includes a fix for that.

cc @sebcrozet.

**Comment by sebcrozet** [comment]
Yes, methods performing slice conversion assume the fields are ordered as they are declared. So I guess `#[repr(C)]` is needed. And I agree this is a must-have to ensure it would work well with e.g. opengl.

**Comment by sebcrozet** [comment]
Fixed by #99.
