### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by aepsil0n** [sebcrozet/nalgebra#89]
@sebcrozet, afaik you are maintaining nalgebra on your own at the moment. Do you need help? With the current breaking changes in the compiler, nalgebra seems to require minor changes being merged and release to crates.io every couple days. Especially since people have started migrating over from cgmath, it would be good to respond to changes in the compiler quickly. I could offer some help in that regard if you want, as I am working with nalgebra almost all the time.

**Comment by sebcrozet** [comment]
Yep, I could use some help. Besides the week-end, I didn't have much time to perform maintenance lately.

As you contributed quite a lot to this project, I think it is natural to trust you and give you some write access.

**Comment by aepsil0n** [comment]
I appreciate the trust. I'll do my best to contribute further. ^^

**Comment by aepsil0n** [comment]
btw can I also bump the version an publish to crates.io?

**Comment by sebcrozet** [comment]
As long as you don't release bump the major version number, I’m okay with that :)
